### PR TITLE
Fix OSX build

### PR DESCRIPTION
**Pull request by CarterLi**
Well, the emulator does build and run on macOS, but fails to boot any games. It seems something else is broken

### CODE REVIEW

**Comment by iCatButler** [comment]
I think the failure to boot games could be a problem with configuration structure members not being initialised. The code for loading and saving these values appears to all be platform specific, using the registry under Windows.

**Comment by CarterLi** [comment]
> configuration structure members not being initialised

Could you please point out where the initializing code is? I'll try to fix it.

**Comment by iCatButler** [comment]
The overclock members were added in this commit:
https://github.com/iCatButler/pcsxr/commit/1a30cfb9510d4e46960010735d26a344f75cb328
Initial PGXP setting here:
https://github.com/iCatButler/pcsxr/commit/a64d62be4b433fcad3804d3bb616bdf4f13504f4
And PGXP CPU mode selection here:
https://github.com/iCatButler/pcsxr/commit/42176205ce9ed9aa2408d4042a816fe5cd082519

The members are set based on new dialogue options in the configuration menu, they're then stored and retrieved from the Windows registry in the SaveConfig() and LoadConfig() functions of win32/gui/ConfigurePlugins.c using SetKeyV() and QueryKeyV() respectively.

The config struct is actually memset to 0 in the WinMain() function of win32/gui/WndMain.c prior to calling LoadConfig(), so that would initialise the member variables to 0. I couldn't find a similar call in the macosx folder, but it may be there.

That said, even when I comment out the relevant memset and QueryKeyV function calls I was still able to boot games, albeit with PGXP and Overclocking features remaining disabled. So it could be something else entirely...

**Comment by CarterLi** [comment]
I tried to get it deeper

``` shell
$ lldb ./build/Release/PCSXR.app/Contents/MacOS/PCSXR
(lldb) target create "./build/Release/PCSXR.app/Contents/MacOS/PCSXR"
Current executable set to './build/Release/PCSXR.app/Contents/MacOS/PCSXR' (x86_64).
(lldb) run
Process 4233 launched: './build/Release/PCSXR.app/Contents/MacOS/PCSXR' (x86_64)
Process 4233 stopped
* thread #1: tid = 0x12a39, 0x0000000000000000, queue = 'com.apple.main-thread', activity = 'sendAction:', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000000000000
error: memory read failed for 0x0
(lldb) bt
* thread #1: tid = 0x12a39, 0x0000000000000000, queue = 'com.apple.main-thread', activity = 'sendAction:', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000000000000
    frame #1: 0x0000000100002589 PCSXR`SysInit [inlined] psxSetPGXPMode(pgxpMode=<unavailable>) + 10 at r3000a.c:281 [opt]
    frame #2: 0x000000010000257f PCSXR`SysInit [inlined] EmuSetPGXPMode(pgxpMode=<unavailable>) at psxcommon.c:85 [opt]
    frame #3: 0x000000010000257f PCSXR`SysInit [inlined] EmuInit + 192 at psxcommon.c:42 [opt]
    frame #4: 0x00000001000024bf PCSXR`SysInit + 15 at main.m:126 [opt]
    frame #5: 0x000000010000e02f PCSXR`+[EmuThread run](self=<unavailable>, _cmd=<unavailable>) + 127 at EmuThread.m:220 [opt]
    frame #6: 0x0000000100003c99 PCSXR`-[PcsxrController runURL:](self=<unavailable>, _cmd=<unavailable>, url=<unavailable>) + 377 at PcsxrController.m:319 [opt]
    frame #7: 0x000000010005f849 PCSXR`-[RecentItemsMenu openRecentItem:](self=<unavailable>, _cmd=<unavailable>, sender=<unavailable>) + 89 at RecentItemsMenu.m:91 [opt]
    frame #8: 0x00007fff882ba07a libsystem_trace.dylib`_os_activity_initiate + 75
    frame #9: 0x00007fff8423ddbd AppKit`-[NSApplication sendAction:to:from:] + 460
    frame #10: 0x00007fff8423db57 AppKit`-[NSMenuItem _corePerformAction] + 336
    frame #11: 0x00007fff8423d8b7 AppKit`-[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
    frame #12: 0x00007fff882ba07a libsystem_trace.dylib`_os_activity_initiate + 75
    frame #13: 0x00007fff842cfe54 AppKit`-[NSMenu performActionForItemAtIndex:] + 131
    frame #14: 0x00007fff842cfdc7 AppKit`-[NSMenu _internalPerformActionForItemAtIndex:] + 35
    frame #15: 0x00007fff842cfc1f AppKit`-[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 107
    frame #16: 0x00007fff84174fd9 AppKit`NSSLMMenuEventHandler + 708
    frame #17: 0x00007fff96a007be HIToolbox`DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1231
    frame #18: 0x00007fff969ffc48 HIToolbox`SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 404
    frame #19: 0x00007fff96a159e6 HIToolbox`SendEventToEventTarget + 40
    frame #20: 0x00007fff96a5f99a HIToolbox`SendHICommandEvent(unsigned int, HICommand const*, unsigned int, unsigned int, unsigned char, void const*, OpaqueEventTargetRef*, OpaqueEventTargetRef*, OpaqueEventRef**) + 411
    frame #21: 0x00007fff96a8ad5b HIToolbox`SendMenuCommandWithContextAndModifiers + 59
    frame #22: 0x00007fff96a8ad0c HIToolbox`SendMenuItemSelectedEvent + 188
    frame #23: 0x00007fff96a8abe8 HIToolbox`FinishMenuSelection(SelectionData*, MenuResult*, MenuResult*) + 96
    frame #24: 0x00007fff96a8b596 HIToolbox`MenuSelectCore(MenuData*, Point, double, unsigned int, OpaqueMenuRef**, unsigned short*) + 711
    frame #25: 0x00007fff96a8b230 HIToolbox`_HandleMenuSelection2 + 460
    frame #26: 0x00007fff841600fa AppKit`_NSHandleCarbonMenuEvent + 277
    frame #27: 0x00007fff83fd513d AppKit`_DPSNextEvent + 1906
    frame #28: 0x00007fff83fd4226 AppKit`-[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
    frame #29: 0x00007fff83fc8d80 AppKit`-[NSApplication run] + 682
    frame #30: 0x00007fff83f92368 AppKit`NSApplicationMain + 1176
    frame #31: 0x0000000100002432 PCSXR`main(argc=<unavailable>, argv=0x00007fff5fbff868) + 498 at main.m:103 [opt]
    frame #32: 0x00007fff919365ad libdyld.dylib`start + 1
    frame #33: 0x00007fff919365ad libdyld.dylib`start + 1
(lldb) p psxCpu
(R3000Acpu *) $0 = 0x0000000100099060
(lldb) p psxCpu->SetPGXPMode
(void (*)(u32)) $1 = 0x0000000000000000
(lldb) kill
Process 4233 exited with status = 9 (0x00000009)
(lldb) exit
```

It shows that the problem goes here: https://github.com/iCatButler/pcsxr/blob/master/libpcsxcore/r3000a.c#L281
`psxCpu->SetPGXPMode` is NULL. I think we should init it commonly. Do you have any ideas?

**Comment by iCatButler** [comment]
I see. That pointer should be statically initialised but the code was a bit messy (slightly odd header/source file relationship). I think I may have fixed it now, can you try this: https://github.com/iCatButler/pcsxr/commit/595034707b7ee346e575c6776327794ab5535ce8

**Comment by CarterLi** [comment]
It doesn't work. The generated error and stack trace are exactly the same.
I notice that you change code that specified to x86, but all the builds in modern macOS are x64 version. Don't know it matters or not.

**Comment by iCatButler** [comment]
I think that's probably it. The mode changes in the recompiler core are handled by switching between multiple function lookup tables in iR3000A.c, which is duplicated as iR3000A-64.c for the x86_46 version. The changes should be pretty simple to duplicate unless the two versions are very different.

I'm quite surprised how far the Windows and MacOS versions have diverged, I've not been able to get the 64-bit version to work in Windows yet, if I can't get it to run properly I can always make the relevant changes and check the file in.

As this only affects the recompiler you might be able to run games by switching to just the interpreter core.

**Comment by iCatButler** [comment]
Okay, I've now got the 64-bit version working on Windows and have added the PGXP integration code to that version of the dynarec: https://github.com/iCatButler/pcsxr/commit/36ef7277127e1010c296ce8792f74934c2ee9d2f

I'm not sure whether to tidy up and submit the changes to get it running under Windows though, or just to shelve it for now, most of the closed source plugins won't be compiled for 64-bit (like Pete's GL 2.9 plugin).

**Comment by CarterLi** [comment]
It works, the performance is not very good though.
Thanks for your help

## 

We should always give functions a return type, despite the function being a noop ;)

**Pull request merged**
